apiVersion: v1
kind: Pod
metadata:
  name: requests-pod2
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main
    resources:
      requests:
        cpu: 700m
        memory: 10Mi
